server {
    listen 443 ssl;
    server_name jaeholee.42.fr;

    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_certificate     /etc/ssl/certs/inception.crt;
    ssl_certificate_key /etc/ssl/private/inception.key;

    root /var/www/html;
    index index.php index.html;

    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { log_not_found off; access_log off; }

    # WordPress front controller
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # deny hidden files
    location ~ /\. {
        deny all;
    }

    # PHP
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        fastcgi_pass wordpress:9000;
    }
}
